function linear_approx(sector)
    
    props = {'DIVIDEND_YIELD', ...
             'LOW_PX_TO_BOOK_RATIO', ... 
             'PE_RATIO', ...
             'SALES_GROWTH', ...
             'EBITDA', ...
             'ASSET_TURNOVER',  ...
             'TOT_DEBT_TOTAL_ASSET', ... 
             'CF_CAP_EXPEND_PRPTY_ADD', ... 
             'REL_SHR_PX_MOMENTUM', ... 
             'TOT_MKT_VAL', ... 
             'RETURN_COM_EQY', ... 
             'PROF_MARGIN'};

    % each equity in sector
    for i = 1 : 5
        
        len = length(sector(i).PX_LAST);
        
        % input
        x1 = [sector(i).DIVIDEND_YIELD, ...
             sector(i).LOW_PX_TO_BOOK_RATIO, ... 
             sector(i).PE_RATIO, ...
             sector(i).SALES_GROWTH, ...
             sector(i).EBITDA, ...
             sector(i).ASSET_TURNOVER, ...
             sector(i).TOT_DEBT_TOTAL_ASSET, ...
             sector(i).CF_CAP_EXPEND_PRPTY_ADD, ...
             sector(i).REL_SHR_PX_MOMENTUM, ...
             sector(i).TOT_MKT_VAL, ...
             sector(i).RETURN_COM_EQY, ...
             sector(i).PROF_MARGIN, ...
            ];
        
        y1 = sector(i).PX_LAST;
        y = oscillation(y1);
        
        for j = 1 : 12
            
            x = oscillation(x1(:, j));
            
            % OLS linear approximation
            xols = [ones(len,1) x];
            bols = inv(xols' * xols) * xols' * y;
            rsqols(i) = var(xols * bols) / var(y);

            % Polynomial 
            xp = [ones(len,1) x x.^2];
            bp = inv(xp'*xp)*xp'*y;
            rsqp(i) = var(xp*bp)/var(y);
            
            RSQ(i,:) = [rsqols(i) rsqp(i)];
            
            fprintf('\nName: %s', char(sector(i).name));
            fprintf('\nEquity Factor: %s', char(props(i)));
            fprintf('\nOLS: %f', RSQ(i, 1));
            fprintf('\nPoly: %f', RSQ(i, 2));
            fprintf('\n\n\n');
        end
    end
end

function [y] = oscillation(x)
    y = ((2 * x) ./ (max(x)-min(x))) - ((max(x)+min(x))/(max(x)-min(x)));
end
